// scripts/generateRegisterModules.js
const fs = require('fs');
const path = require('path');

const levels = ['n5', 'n4', 'n3', 'n2', 'n1'];
const baseDir = path.join(__dirname, '../assets/data_EXAMS');

const scanFiles = () => {
  const textFiles = [];
  const audioFiles = [];
  const imageFiles = [];
  
  for (const level of levels) {
    const levelDir = path.join(baseDir, level);
    if (!fs.existsSync(levelDir)) {
      console.log(`⚠️ Thư mục ${level} chưa tồn tại, bỏ qua`);
      continue;
    }
    
    const files = fs.readdirSync(levelDir);
    for (const file of files) {
      if (file.endsWith('_text.json')) {
        textFiles.push({ level, name: file.replace('.json', '') });
      } else if (file.endsWith('_audio.json')) {
        audioFiles.push({ level, name: file.replace('.json', '') });
      } else if (file.endsWith('_image.json')) {
        imageFiles.push({ level, name: file.replace('.json', '') });
      }
    }
  }
  
  console.log(`📁 Tìm thấy: ${textFiles.length} text, ${audioFiles.length} audio, ${imageFiles.length} image`);
  
  // Tạo nội dung registerModules.ts
  let imports = '';
  let textExports = 'export const textModules = {\n';
  let audioExports = 'export const audioModules = {\n';
  let imageExports = 'export const imageModules = {\n';
  
  for (const item of textFiles) {
    imports += `import ${item.name} from "./${item.level}/${item.name}.json";\n`;
    textExports += `  ${item.name},\n`;
  }
  
  for (const item of audioFiles) {
    imports += `import ${item.name} from "./${item.level}/${item.name}.json";\n`;
    audioExports += `  ${item.name},\n`;
  }
  
  for (const item of imageFiles) {
    imports += `import ${item.name} from "./${item.level}/${item.name}.json";\n`;
    imageExports += `  ${item.name},\n`;
  }
  
  textExports += '};\n';
  audioExports += '};\n';
  imageExports += '};\n';
  
  const content = `// Auto-generated file - DO NOT EDIT
// Generated by scripts/generateRegisterModules.js

${imports}
${textExports}
${audioExports}
${imageExports}

// Helper functions
export const getTextModule = (name: string) => textModules[name as keyof typeof textModules];
export const getAudioModule = (name: string) => audioModules[name as keyof typeof audioModules];
export const getImageModule = (name: string) => imageModules[name as keyof typeof imageModules];
`;
  
  const outputPath = path.join(baseDir, 'registerModules.ts');
  fs.writeFileSync(outputPath, content);
  console.log(`✅ Đã tạo registerModules.ts tại ${outputPath}`);
};

scanFiles();