// // Auto-generated file - DO NOT EDIT
// // Generated by scripts/generateRegisterModules.js


// export const textModules = {
// };

// export const audioModules = {
// };

// export const imageModules = {
// };


// // Helper functions
// export const getTextModule = (name: string) => textModules[name as keyof typeof textModules];
// export const getAudioModule = (name: string) => audioModules[name as keyof typeof audioModules];
// export const getImageModule = (name: string) => imageModules[name as keyof typeof imageModules];
