import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const filePath = join(__dirname, '../artifacts/mirai-jp/assets/vocab/n2_mimikara.json');

const existing = JSON.parse(readFileSync(filePath, 'utf8'));
const existingSet = new Set(existing.map(e => e.kanji));

const extra = [
  {kanji:"間",hira:"あいだ",han:"Gian",nghia:"khoảng cách, khoảng thời gian"},
  {kanji:"開く",hira:"あく",han:"Khai",nghia:"mở ra, trống"},
  {kanji:"朝",hira:"あさ",han:"Triêu",nghia:"buổi sáng"},
  {kanji:"足",hira:"あし",han:"Túc",nghia:"chân, bàn chân"},
  {kanji:"頭",hira:"あたま",han:"Đầu",nghia:"đầu, trí não"},
  {kanji:"雨",hira:"あめ",han:"Vũ",nghia:"mưa"},
  {kanji:"歩く",hira:"あるく",han:"Bộ",nghia:"đi bộ"},
  {kanji:"言う",hira:"いう",han:"Ngôn",nghia:"nói, bảo"},
  {kanji:"家",hira:"いえ",han:"Gia",nghia:"nhà"},
  {kanji:"意味",hira:"いみ",han:"Ý nghĩa",nghia:"ý nghĩa"},
  {kanji:"入る",hira:"はいる",han:"Nhập",nghia:"vào, nhập vào"},
  {kanji:"上",hira:"うえ",han:"Thượng",nghia:"phía trên"},
  {kanji:"後ろ",hira:"うしろ",han:"Hậu",nghia:"phía sau"},
  {kanji:"歌",hira:"うた",han:"Ca",nghia:"bài hát"},
  {kanji:"腕",hira:"うで",han:"Uyển",nghia:"cánh tay, kỹ năng"},
  {kanji:"絵",hira:"え",han:"Hoạ",nghia:"tranh, hình vẽ"},
  {kanji:"映画",hira:"えいが",han:"Điện ảnh",nghia:"phim, điện ảnh"},
  {kanji:"駅",hira:"えき",han:"Dịch",nghia:"nhà ga"},
  {kanji:"顔",hira:"かお",han:"Diện",nghia:"khuôn mặt"},
  {kanji:"体",hira:"からだ",han:"Thể",nghia:"cơ thể"},
  {kanji:"貸す",hira:"かす",han:"Tá",nghia:"cho mượn, cho thuê"},
  {kanji:"勝つ",hira:"かつ",han:"Thắng",nghia:"thắng, chiến thắng"},
  {kanji:"借りる",hira:"かりる",han:"Tá",nghia:"mượn, vay"},
  {kanji:"考え",hira:"かんがえ",han:"Khảo",nghia:"suy nghĩ, ý tưởng"},
  {kanji:"記憶",hira:"きおく",han:"Ký ức",nghia:"ký ức, trí nhớ"},
  {kanji:"季節",hira:"きせつ",han:"Quý tiết",nghia:"mùa, mùa vụ"},
  {kanji:"消える",hira:"きえる",han:"Tiêu",nghia:"biến mất, tắt"},
  {kanji:"空気",hira:"くうき",han:"Không khí",nghia:"không khí"},
  {kanji:"口",hira:"くち",han:"Khẩu",nghia:"miệng"},
  {kanji:"車",hira:"くるま",han:"Xa",nghia:"xe, ô tô"},
  {kanji:"言葉",hira:"ことば",han:"Ngôn từ",nghia:"ngôn từ, lời nói"},
  {kanji:"声",hira:"こえ",han:"Thanh",nghia:"giọng nói"},
  {kanji:"子供",hira:"こども",han:"Tử",nghia:"trẻ em"},
  {kanji:"作る",hira:"つくる",han:"Tác",nghia:"tạo ra, làm ra"},
  {kanji:"今年",hira:"ことし",han:"Kim niên",nghia:"năm nay"},
  {kanji:"仕事",hira:"しごと",han:"Sự nghiệp",nghia:"công việc"},
  {kanji:"時間",hira:"じかん",han:"Thời gian",nghia:"thời gian"},
  {kanji:"事情",hira:"じじょう",han:"Sự tình",nghia:"hoàn cảnh, tình tiết"},
  {kanji:"下",hira:"した",han:"Hạ",nghia:"phía dưới"},
  {kanji:"写真",hira:"しゃしん",han:"Xạ chân",nghia:"ảnh, hình ảnh"},
  {kanji:"趣味",hira:"しゅみ",han:"Thú vị",nghia:"sở thích"},
  {kanji:"新聞",hira:"しんぶん",han:"Tân văn",nghia:"báo, tờ báo"},
  {kanji:"水",hira:"みず",han:"Thuỷ",nghia:"nước"},
  {kanji:"生活",hira:"せいかつ",han:"Sinh hoạt",nghia:"cuộc sống, sinh hoạt"},
  {kanji:"先生",hira:"せんせい",han:"Tiên sinh",nghia:"thầy giáo, bác sĩ"},
  {kanji:"空",hira:"そら",han:"Không",nghia:"bầu trời"},
  {kanji:"立場",hira:"たちば",han:"Lập trường",nghia:"lập trường, quan điểm"},
  {kanji:"力",hira:"ちから",han:"Lực",nghia:"sức mạnh, lực"},
  {kanji:"地図",hira:"ちず",han:"Địa đồ",nghia:"bản đồ"},
  {kanji:"机",hira:"つくえ",han:"Kỷ",nghia:"bàn, bàn học"},
  {kanji:"都合",hira:"つごう",han:"Đô hợp",nghia:"sự thuận tiện, tình huống"},
  {kanji:"手",hira:"て",han:"Thủ",nghia:"tay"},
  {kanji:"出口",hira:"でぐち",han:"Lối ra",nghia:"lối ra"},
  {kanji:"電話",hira:"でんわ",han:"Điện thoại",nghia:"điện thoại"},
  {kanji:"友達",hira:"ともだち",han:"Bằng hữu",nghia:"bạn bè"},
  {kanji:"中",hira:"なか",han:"Trung",nghia:"bên trong, giữa"},
  {kanji:"名前",hira:"なまえ",han:"Danh",nghia:"tên"},
  {kanji:"荷物",hira:"にもつ",han:"Hành lý",nghia:"hành lý, đồ đạc"},
  {kanji:"場所",hira:"ばしょ",han:"Trường sở",nghia:"nơi chốn"},
  {kanji:"花",hira:"はな",han:"Hoa",nghia:"hoa"},
  {kanji:"話",hira:"はなし",han:"Thoại",nghia:"câu chuyện, bàn bạc"},
  {kanji:"春",hira:"はる",han:"Xuân",nghia:"mùa xuân"},
  {kanji:"反対",hira:"はんたい",han:"Phản đối",nghia:"phản đối, ngược lại"},
  {kanji:"人",hira:"ひと",han:"Nhân",nghia:"người"},
  {kanji:"病院",hira:"びょういん",han:"Bệnh viện",nghia:"bệnh viện"},
  {kanji:"昼",hira:"ひる",han:"Trú",nghia:"buổi trưa"},
  {kanji:"冬",hira:"ふゆ",han:"Đông",nghia:"mùa đông"},
  {kanji:"部屋",hira:"へや",han:"Phòng",nghia:"căn phòng"},
  {kanji:"本",hira:"ほん",han:"Bản",nghia:"sách"},
  {kanji:"前",hira:"まえ",han:"Tiền",nghia:"phía trước, trước đây"},
  {kanji:"窓",hira:"まど",han:"Song",nghia:"cửa sổ"},
  {kanji:"道",hira:"みち",han:"Đạo",nghia:"đường, con đường"},
  {kanji:"店",hira:"みせ",han:"Điếm",nghia:"cửa hàng"},
  {kanji:"耳",hira:"みみ",han:"Nhĩ",nghia:"tai"},
  {kanji:"目",hira:"め",han:"Mục",nghia:"mắt"},
  {kanji:"山",hira:"やま",han:"Sơn",nghia:"núi"},
  {kanji:"夢",hira:"ゆめ",han:"Mộng",nghia:"giấc mơ"},
  {kanji:"予定",hira:"よてい",han:"Dự định",nghia:"dự định, kế hoạch"},
  {kanji:"夜",hira:"よる",han:"Dạ",nghia:"buổi tối, đêm"},
  {kanji:"来年",hira:"らいねん",han:"Lai niên",nghia:"năm sau"},
  {kanji:"旅行",hira:"りょこう",han:"Lữ hành",nghia:"du lịch"},
  {kanji:"両親",hira:"りょうしん",han:"Lưỡng thân",nghia:"cha mẹ, bố mẹ"},
  {kanji:"若い",hira:"わかい",han:"Nhược",nghia:"trẻ, còn trẻ"},
  {kanji:"食事",hira:"しょくじ",han:"Thực sự",nghia:"bữa ăn"},
  {kanji:"音楽",hira:"おんがく",han:"Âm nhạc",nghia:"âm nhạc"},
  {kanji:"地球",hira:"ちきゅう",han:"Địa cầu",nghia:"trái đất"},
  {kanji:"宇宙",hira:"うちゅう",han:"Vũ trụ",nghia:"vũ trụ"},
  {kanji:"森",hira:"もり",han:"Lâm",nghia:"rừng"},
  {kanji:"川",hira:"かわ",han:"Xuyên",nghia:"sông, suối"},
  {kanji:"海",hira:"うみ",han:"Hải",nghia:"biển"},
  {kanji:"池",hira:"いけ",han:"Trì",nghia:"ao"},
  {kanji:"草",hira:"くさ",han:"Thảo",nghia:"cỏ, cây cỏ"},
  {kanji:"木",hira:"き",han:"Mộc",nghia:"cây, gỗ"},
  {kanji:"石",hira:"いし",han:"Thạch",nghia:"đá"},
  {kanji:"火",hira:"ひ",han:"Hoả",nghia:"lửa"},
  {kanji:"風",hira:"かぜ",han:"Phong",nghia:"gió"},
  {kanji:"雪",hira:"ゆき",han:"Tuyết",nghia:"tuyết"},
  {kanji:"太陽",hira:"たいよう",han:"Thái dương",nghia:"mặt trời"},
  {kanji:"月",hira:"つき",han:"Nguyệt",nghia:"mặt trăng"},
  {kanji:"星",hira:"ほし",han:"Tinh",nghia:"ngôi sao"},
  {kanji:"光",hira:"ひかり",han:"Quang",nghia:"ánh sáng"},
  {kanji:"成功",hira:"せいこう",han:"Thành công",nghia:"thành công"},
  {kanji:"失敗",hira:"しっぱい",han:"Thất bại",nghia:"thất bại"},
  {kanji:"経営",hira:"けいえい",han:"Kinh doanh",nghia:"kinh doanh, quản lý"},
  {kanji:"企業",hira:"きぎょう",han:"Doanh nghiệp",nghia:"công ty, doanh nghiệp"},
  {kanji:"従業員",hira:"じゅうぎょういん",han:"Nhân viên",nghia:"nhân viên"},
  {kanji:"就職",hira:"しゅうしょく",han:"Tựu chức",nghia:"xin việc, tìm việc"},
  {kanji:"退職",hira:"たいしょく",han:"Thối chức",nghia:"nghỉ việc, từ chức"},
  {kanji:"給料",hira:"きゅうりょう",han:"Cấp liệu",nghia:"lương"},
  {kanji:"残業",hira:"ざんぎょう",han:"Tàn nghiệp",nghia:"làm thêm giờ"},
  {kanji:"休暇",hira:"きゅうか",han:"Hưu giả",nghia:"kỳ nghỉ"},
  {kanji:"契約",hira:"けいやく",han:"Khế ước",nghia:"hợp đồng"},
  {kanji:"評判",hira:"ひょうばん",han:"Bình phán",nghia:"danh tiếng, đánh giá"},
  {kanji:"実力",hira:"じつりょく",han:"Thực lực",nghia:"thực lực, năng lực thực tế"},
  {kanji:"素質",hira:"そしつ",han:"Tố chất",nghia:"tố chất, tài năng bẩm sinh"},
  {kanji:"経歴",hira:"けいれき",han:"Kinh lịch",nghia:"kinh nghiệm, lý lịch"},
  {kanji:"業績",hira:"ぎょうせき",han:"Nghiệp tích",nghia:"thành tích, kết quả kinh doanh"},
  {kanji:"同僚",hira:"どうりょう",han:"Đồng liêu",nghia:"đồng nghiệp"},
  {kanji:"上司",hira:"じょうし",han:"Thượng ti",nghia:"cấp trên"},
  {kanji:"部下",hira:"ぶか",han:"Bộ hạ",nghia:"cấp dưới, nhân viên dưới quyền"},
  {kanji:"先輩",hira:"せんぱい",han:"Tiên bối",nghia:"đàn anh, tiền bối"},
  {kanji:"後輩",hira:"こうはい",han:"Hậu bối",nghia:"đàn em, hậu bối"},
  {kanji:"友人",hira:"ゆうじん",han:"Hữu nhân",nghia:"bạn bè"},
  {kanji:"知人",hira:"ちじん",han:"Tri nhân",nghia:"người quen"},
  {kanji:"他人",hira:"たにん",han:"Tha nhân",nghia:"người khác, người ngoài"},
  {kanji:"本人",hira:"ほんにん",han:"Bản nhân",nghia:"đương sự, chính người đó"},
  {kanji:"国民",hira:"こくみん",han:"Quốc dân",nghia:"nhân dân, quốc dân"},
  {kanji:"市民",hira:"しみん",han:"Thị dân",nghia:"công dân, thị dân"},
  {kanji:"住民",hira:"じゅうみん",han:"Trú dân",nghia:"cư dân, người dân sống ở đó"},
  {kanji:"患者",hira:"かんじゃ",han:"Hoạn giả",nghia:"bệnh nhân"},
  {kanji:"医者",hira:"いしゃ",han:"Y giả",nghia:"bác sĩ"},
  {kanji:"警察",hira:"けいさつ",han:"Cảnh sát",nghia:"cảnh sát"},
  {kanji:"弁護士",hira:"べんごし",han:"Biện hộ sĩ",nghia:"luật sư"},
  {kanji:"政治家",hira:"せいじか",han:"Chính trị gia",nghia:"chính trị gia"},
  {kanji:"科学者",hira:"かがくしゃ",han:"Khoa học giả",nghia:"nhà khoa học"},
  {kanji:"研究者",hira:"けんきゅうしゃ",han:"Nghiên cứu giả",nghia:"nhà nghiên cứu"},
  {kanji:"作家",hira:"さっか",han:"Tác gia",nghia:"nhà văn"},
  {kanji:"芸術家",hira:"げいじゅつか",han:"Nghệ thuật gia",nghia:"nghệ sĩ"},
  {kanji:"教師",hira:"きょうし",han:"Giáo sư",nghia:"giáo viên"},
  {kanji:"学者",hira:"がくしゃ",han:"Học giả",nghia:"học giả"},
  {kanji:"専門家",hira:"せんもんか",han:"Chuyên môn gia",nghia:"chuyên gia"},
  {kanji:"記者",hira:"きしゃ",han:"Ký giả",nghia:"nhà báo, phóng viên"},
  {kanji:"選手",hira:"せんしゅ",han:"Tuyển thủ",nghia:"vận động viên, tuyển thủ"},
  {kanji:"観客",hira:"かんきゃく",han:"Quan khách",nghia:"khán giả"},
  {kanji:"読者",hira:"どくしゃ",han:"Độc giả",nghia:"độc giả"},
  {kanji:"消費者",hira:"しょうひしゃ",han:"Tiêu phí giả",nghia:"người tiêu dùng"},
  {kanji:"生産者",hira:"せいさんしゃ",han:"Sản xuất giả",nghia:"nhà sản xuất"},
  {kanji:"参加者",hira:"さんかしゃ",han:"Tham gia giả",nghia:"người tham gia"},
  {kanji:"関係者",hira:"かんけいしゃ",han:"Quan hệ giả",nghia:"người liên quan"},
  {kanji:"団体",hira:"だんたい",han:"Đoàn thể",nghia:"đoàn thể, tổ chức"},
  {kanji:"会社",hira:"かいしゃ",han:"Công ty",nghia:"công ty"},
  {kanji:"学校",hira:"がっこう",han:"Học hiệu",nghia:"trường học"},
  {kanji:"大学",hira:"だいがく",han:"Đại học",nghia:"đại học"},
  {kanji:"政府",hira:"せいふ",han:"Chính phủ",nghia:"chính phủ"},
  {kanji:"時代",hira:"じだい",han:"Thời đại",nghia:"thời đại"},
  {kanji:"現在",hira:"げんざい",han:"Hiện tại",nghia:"hiện tại"},
  {kanji:"過去",hira:"かこ",han:"Quá khứ",nghia:"quá khứ"},
  {kanji:"未来",hira:"みらい",han:"Vị lai",nghia:"tương lai"},
  {kanji:"期間",hira:"きかん",han:"Kỳ gian",nghia:"kỳ hạn, thời gian"},
  {kanji:"長期",hira:"ちょうき",han:"Trường kỳ",nghia:"dài hạn"},
  {kanji:"短期",hira:"たんき",han:"Đoản kỳ",nghia:"ngắn hạn"},
  {kanji:"瞬間",hira:"しゅんかん",han:"Thuấn gian",nghia:"khoảnh khắc"},
  {kanji:"段階",hira:"だんかい",han:"Đoạn giai",nghia:"giai đoạn, bước"},
  {kanji:"手続き",hira:"てつづき",han:"Thủ tục",nghia:"thủ tục, quy trình"},
  {kanji:"手間",hira:"てま",han:"Thủ gian",nghia:"công sức, thời gian bỏ ra"},
  {kanji:"見通し",hira:"みとおし",han:"Kiến thông",nghia:"triển vọng, dự báo"},
  {kanji:"見込み",hira:"みこみ",han:"Kiến đăng",nghia:"triển vọng, hy vọng"},
  {kanji:"見解",hira:"けんかい",han:"Kiến giải",nghia:"quan điểm, ý kiến"},
  {kanji:"本物",hira:"ほんもの",han:"Bản vật",nghia:"vật thật, chính hàng"},
  {kanji:"偽物",hira:"にせもの",han:"Nguỵ vật",nghia:"đồ giả, hàng giả"},
  {kanji:"品物",hira:"しなもの",han:"Phẩm vật",nghia:"hàng hoá, đồ vật"},
  {kanji:"物事",hira:"ものごと",han:"Vật sự",nghia:"sự vật, mọi thứ"},
  {kanji:"出来事",hira:"できごと",han:"Xuất lai sự",nghia:"sự kiện, việc xảy ra"},
  {kanji:"暮らし",hira:"くらし",han:"Mộ",nghia:"cuộc sống, sinh kế"},
  {kanji:"生き方",hira:"いきかた",han:"Sinh phương",nghia:"lối sống, cách sống"},
  {kanji:"考え方",hira:"かんがえかた",han:"Tư phương",nghia:"cách suy nghĩ, quan điểm"},
  {kanji:"見方",hira:"みかた",han:"Kiến phương",nghia:"cách nhìn, quan điểm"},
  {kanji:"使い方",hira:"つかいかた",han:"Sử phương",nghia:"cách sử dụng"},
  {kanji:"働き方",hira:"はたらきかた",han:"Lao phương",nghia:"cách làm việc"},
  {kanji:"解決策",hira:"かいけつさく",han:"Giải quyết sách",nghia:"biện pháp giải quyết"},
  {kanji:"改善策",hira:"かいぜんさく",han:"Cải thiện sách",nghia:"biện pháp cải thiện"},
  {kanji:"話し方",hira:"はなしかた",han:"Thoại phương",nghia:"cách nói chuyện"},
  {kanji:"書き方",hira:"かきかた",han:"Thư phương",nghia:"cách viết"},
  {kanji:"気がかり",hira:"きがかり",han:"Khí quải",nghia:"mối lo lắng, điều băn khoăn"},
  {kanji:"心がけ",hira:"こころがけ",han:"Tâm quải",nghia:"sự chú ý, tinh thần cố gắng"},
  {kanji:"心構え",hira:"こころがまえ",han:"Tâm cấu",nghia:"tư thế tâm lý, sự chuẩn bị tinh thần"},
  {kanji:"言い訳",hira:"いいわけ",han:"Ngôn dịch",nghia:"lý do, lời giải thích"},
  {kanji:"申し込み",hira:"もうしこみ",han:"Thân hậm",nghia:"sự đăng ký, đơn xin"},
  {kanji:"申請",hira:"しんせい",han:"Thân thỉnh",nghia:"đơn xin, yêu cầu"},
  {kanji:"請求",hira:"せいきゅう",han:"Thỉnh cầu",nghia:"yêu cầu, đòi hỏi"},
  {kanji:"依頼",hira:"いらい",han:"Y lai",nghia:"nhờ cậy, ủy thác"},
  {kanji:"要望",hira:"ようぼう",han:"Yêu vọng",nghia:"nguyện vọng, mong muốn"},
  {kanji:"期待",hira:"きたい",han:"Kỳ đãi",nghia:"kỳ vọng, mong đợi"},
  {kanji:"目的",hira:"もくてき",han:"Mục đích",nghia:"mục đích"},
  {kanji:"程度",hira:"ていど",han:"Trình độ",nghia:"mức độ, trình độ"},
  {kanji:"水準",hira:"すいじゅん",han:"Thuỷ chuẩn",nghia:"mức, tiêu chuẩn"},
  {kanji:"平均",hira:"へいきん",han:"Bình quân",nghia:"bình quân, trung bình"},
  {kanji:"最大",hira:"さいだい",han:"Tối đại",nghia:"lớn nhất, tối đa"},
  {kanji:"最小",hira:"さいしょう",han:"Tối tiểu",nghia:"nhỏ nhất, tối thiểu"},
  {kanji:"最高",hira:"さいこう",han:"Tối cao",nghia:"cao nhất, tốt nhất"},
  {kanji:"最低",hira:"さいてい",han:"Tối đê",nghia:"thấp nhất, tệ nhất"},
  {kanji:"最初",hira:"さいしょ",han:"Tối sơ",nghia:"đầu tiên, ban đầu"},
  {kanji:"最後",hira:"さいご",han:"Tối hậu",nghia:"cuối cùng"},
  {kanji:"一番",hira:"いちばん",han:"Nhất ban",nghia:"số một, nhất"},
  {kanji:"数字",hira:"すうじ",han:"Số tự",nghia:"con số, số"},
  {kanji:"比率",hira:"ひりつ",han:"Tỷ suất",nghia:"tỷ lệ, tỷ suất"},
  {kanji:"量",hira:"りょう",han:"Lượng",nghia:"lượng, khối lượng"},
  {kanji:"質",hira:"しつ",han:"Chất",nghia:"chất, chất lượng"},
  {kanji:"形",hira:"かたち",han:"Hình",nghia:"hình dạng, hình thức"},
  {kanji:"様子",hira:"ようす",han:"Dạng tử",nghia:"dáng vẻ, tình hình"},
  {kanji:"条件",hira:"じょうけん",han:"Điều kiện",nghia:"điều kiện"},
  {kanji:"背景",hira:"はいけい",han:"Bối cảnh",nghia:"bối cảnh, nền tảng"},
  {kanji:"過程",hira:"かてい",han:"Quá trình",nghia:"quá trình, giai đoạn"},
  {kanji:"本来",hira:"ほんらい",han:"Bản lai",nghia:"vốn là, ban đầu"},
  {kanji:"そのうえ",hira:"そのうえ",han:"Thượng",nghia:"hơn nữa, thêm vào đó"},
  {kanji:"それどころか",hira:"それどころか",han:"Phi chỉ vậy",nghia:"không những thế, còn hơn thế"},
  {kanji:"たとえ",hira:"たとえ",han:"Giả như",nghia:"dù cho, cho dù"},
  {kanji:"に対して",hira:"にたいして",han:"Đối với",nghia:"đối với, so với"},
  {kanji:"に関して",hira:"にかんして",han:"Liên quan",nghia:"liên quan đến, về việc"},
  {kanji:"に応じて",hira:"におうじて",han:"Ứng theo",nghia:"tùy theo, ứng với"},
  {kanji:"に基づいて",hira:"にもとづいて",han:"Căn cứ vào",nghia:"dựa trên, căn cứ vào"},
  {kanji:"に加えて",hira:"にくわえて",han:"Gia thêm",nghia:"thêm vào đó"},
  {kanji:"だけでなく",hira:"だけでなく",han:"Phi chỉ",nghia:"không chỉ, không phải chỉ"},
  {kanji:"を通じて",hira:"をつうじて",han:"Thông qua",nghia:"thông qua, qua"},
  {kanji:"とはいえ",hira:"とはいえ",han:"Tuy nhiên",nghia:"tuy vậy, tuy thế"},
  {kanji:"しかしながら",hira:"しかしながら",han:"Nhiên nhi",nghia:"tuy nhiên, song"},
  {kanji:"さりげない",hira:"さりげない",han:"Vô ý",nghia:"không khiên cưỡng, tự nhiên"},
  {kanji:"大まか",hira:"おおまか",han:"Đại khái",nghia:"đại khái, tổng quát"},
  {kanji:"無愛想な",hira:"ぶあいそうな",han:"Vô ái tưởng",nghia:"lạnh lùng, thờ ơ"},
  {kanji:"やりがい",hira:"やりがい",han:"Thành tựu",nghia:"ý nghĩa công việc, động lực làm"},
  {kanji:"生きがい",hira:"いきがい",han:"Sinh nhai",nghia:"lý do sống, niềm vui sống"},
  {kanji:"腹が立つ",hira:"はらがたつ",han:"Nổi giận",nghia:"nổi giận, bực mình"},
  {kanji:"気が合う",hira:"きがあう",han:"Hợp ý",nghia:"hợp ý, hợp tính nết"},
  {kanji:"気になる",hira:"きになる",han:"Để ý",nghia:"để ý, bận tâm"},
  {kanji:"気を使う",hira:"きをつかう",han:"Dùng tâm",nghia:"quan tâm, chú ý"},
  {kanji:"気を付ける",hira:"きをつける",han:"Chú ý",nghia:"chú ý, cẩn thận"},
  {kanji:"目を向ける",hira:"めをむける",han:"Hướng mắt",nghia:"chú ý đến, hướng tới"},
  {kanji:"耳を傾ける",hira:"みみをかたむける",han:"Nghiêng tai",nghia:"lắng nghe, chú ý nghe"},
  {kanji:"手を尽くす",hira:"てをつくす",han:"Tận tay",nghia:"làm hết sức, cố gắng hết sức"},
  {kanji:"声をかける",hira:"こえをかける",han:"Cất giọng",nghia:"gọi, lên tiếng hỏi"},
  {kanji:"一歩踏み出す",hira:"いっぽふみだす",han:"Nhất bộ",nghia:"bước ra, tiến thêm một bước"},
  {kanji:"夢を叶える",hira:"ゆめをかなえる",han:"Thành mộng",nghia:"thực hiện ước mơ"},
  {kanji:"目標を立てる",hira:"もくひょうをたてる",han:"Lập mục tiêu",nghia:"đặt mục tiêu"},
  {kanji:"責任を取る",hira:"せきにんをとる",han:"Thụ trách",nghia:"chịu trách nhiệm"},
  {kanji:"約束を守る",hira:"やくそくをまもる",han:"Thủ ước",nghia:"giữ lời hứa"},
  {kanji:"信頼を得る",hira:"しんらいをえる",han:"Tín lại",nghia:"được tin tưởng"},
  {kanji:"尊敬する",hira:"そんけいする",han:"Tôn kính",nghia:"tôn kính, kính trọng"},
  {kanji:"称賛する",hira:"しょうさんする",han:"Xưng tán",nghia:"ca ngợi, khen ngợi"},
  {kanji:"否定する",hira:"ひていする",han:"Phủ định",nghia:"phủ nhận, bác bỏ"},
  {kanji:"肯定する",hira:"こうていする",han:"Khẳng định",nghia:"khẳng định, thừa nhận"},
  {kanji:"反省する",hira:"はんせいする",han:"Phản tỉnh",nghia:"nhìn lại, kiểm điểm"},
  {kanji:"検討する",hira:"けんとうする",han:"Kiểm thảo",nghia:"xem xét, nghiên cứu"},
  {kanji:"向上する",hira:"こうじょうする",han:"Hướng thượng",nghia:"cải thiện, nâng cao"},
  {kanji:"低下する",hira:"ていかする",han:"Để hạ",nghia:"giảm xuống, suy giảm"},
  {kanji:"増加する",hira:"ぞうかする",han:"Tăng thêm",nghia:"tăng lên"},
  {kanji:"減少する",hira:"げんしょうする",han:"Giảm thiểu",nghia:"giảm xuống"},
  {kanji:"拡大する",hira:"かくだいする",han:"Khuếch đại",nghia:"mở rộng"},
  {kanji:"縮小する",hira:"しゅくしょうする",han:"Thu nhỏ",nghia:"thu nhỏ, giảm bớt"},
  {kanji:"統合する",hira:"とうごうする",han:"Thống hợp",nghia:"thống nhất, hợp nhất"},
  {kanji:"変換する",hira:"へんかんする",han:"Biến hoán",nghia:"chuyển đổi, biến đổi"},
  {kanji:"翻訳する",hira:"ほんやくする",han:"Phiên dịch",nghia:"dịch thuật"},
  {kanji:"解釈する",hira:"かいしゃくする",han:"Giải thích",nghia:"giải thích, diễn giải"},
  {kanji:"定義する",hira:"ていぎする",han:"Định nghĩa",nghia:"định nghĩa"},
  {kanji:"区別する",hira:"くべつする",han:"Khu biệt",nghia:"phân biệt, phân loại"},
  {kanji:"承認する",hira:"しょうにんする",han:"Thừa nhận",nghia:"phê duyệt, công nhận"},
  {kanji:"拒否する",hira:"きょひする",han:"Cự phủ",nghia:"từ chối, bác bỏ"},
  {kanji:"廃止する",hira:"はいしする",han:"Phế chỉ",nghia:"bãi bỏ, loại bỏ"},
  {kanji:"導入する",hira:"どうにゅうする",han:"Đạo nhập",nghia:"đưa vào, giới thiệu"},
  {kanji:"実施する",hira:"じっしする",han:"Thực thi",nghia:"thực thi, thực hiện"},
  {kanji:"適用する",hira:"てきようする",han:"Thích dụng",nghia:"áp dụng"},
  {kanji:"含める",hira:"ふくめる",han:"Hàm",nghia:"bao gồm, kể cả"},
  {kanji:"取り込む",hira:"とりこむ",han:"Thủ hậm",nghia:"kết hợp, thu nạp vào"},
  {kanji:"持ち込む",hira:"もちこむ",han:"Trì hậm",nghia:"mang vào, đưa vào"},
  {kanji:"立ち寄る",hira:"たちよる",han:"Lập ký",nghia:"ghé qua, ghé vào"},
  {kanji:"立ち止まる",hira:"たちどまる",han:"Lập chỉ",nghia:"dừng lại, đứng lại"},
  {kanji:"走り出す",hira:"はしりだす",han:"Tẩu xuất",nghia:"chạy ra, bắt đầu chạy"},
  {kanji:"飛び出す",hira:"とびだす",han:"Phi xuất",nghia:"nhảy ra, bay ra"},
  {kanji:"飛び込む",hira:"とびこむ",han:"Phi hậm",nghia:"nhảy vào, lao vào"},
  {kanji:"転ぶ",hira:"ころぶ",han:"Chuyển",nghia:"ngã, vấp"},
  {kanji:"倒れる",hira:"たおれる",han:"Đảo",nghia:"ngã, sụp đổ"},
  {kanji:"起き上がる",hira:"おきあがる",han:"Khởi thượng",nghia:"đứng dậy"},
  {kanji:"押さえる",hira:"おさえる",han:"Ức",nghia:"kiềm chế, giữ lại"},
  {kanji:"抑える",hira:"おさえる",han:"Ức",nghia:"kiềm chế, kiểm soát"},
  {kanji:"放つ",hira:"はなつ",han:"Phóng",nghia:"thả ra, bắn ra"},
  {kanji:"残す",hira:"のこす",han:"Tồn",nghia:"để lại, còn lại"},
  {kanji:"積み立てる",hira:"つみたてる",han:"Tích lập",nghia:"tích lũy, để dành"},
  {kanji:"思い出す",hira:"おもいだす",han:"Tư xuất",nghia:"nhớ lại"},
  {kanji:"実感する",hira:"じっかんする",han:"Thực cảm",nghia:"thực sự cảm nhận, thấm thía"},
  {kanji:"後悔する",hira:"こうかいする",han:"Hối cải",nghia:"hối hận, ăn năn"},
  {kanji:"納得する",hira:"なっとくする",han:"Nạp đắc",nghia:"chấp nhận, thuyết phục được"},
  {kanji:"仕方がない",hira:"しかたがない",han:"Vô phương",nghia:"không có cách nào, đành thôi"},
  {kanji:"気にしない",hira:"きにしない",han:"Vô ý",nghia:"không để ý, không bận tâm"},
  {kanji:"振り回す",hira:"ふりまわす",han:"Chấn hồi",nghia:"vung vẫy, điều khiển"},
  {kanji:"引き回す",hira:"ひきまわす",han:"Dẫn hồi",nghia:"dẫn đi khắp nơi"},
  {kanji:"押し通す",hira:"おしとおす",han:"Áp thông",nghia:"cố thực hiện, kiên trì"},
  {kanji:"言い張る",hira:"いいはる",han:"Ngôn trương",nghia:"cố nói, khăng khăng"},
  {kanji:"言い合う",hira:"いいあう",han:"Ngôn hợp",nghia:"cãi nhau, tranh luận"},
  {kanji:"言い出す",hira:"いいだす",han:"Ngôn xuất",nghia:"nói ra, đề xuất"},
  {kanji:"言い切る",hira:"いいきる",han:"Ngôn thiết",nghia:"khẳng định, nói dứt khoát"},
  {kanji:"聞き流す",hira:"ききながす",han:"Văn lưu",nghia:"lờ đi, nghe qua tai"},
  {kanji:"聞き取る",hira:"ききとる",han:"Văn thủ",nghia:"nghe hiểu, ghi lấy"},
  {kanji:"読み取る",hira:"よみとる",han:"Độc thủ",nghia:"đọc hiểu, nhận ra"},
  {kanji:"書き取る",hira:"かきとる",han:"Thư thủ",nghia:"ghi lại, viết lấy"},
  {kanji:"書き込む",hira:"かきこむ",han:"Thư hậm",nghia:"viết vào, điền vào"},
  {kanji:"打ち合わせ",hira:"うちあわせ",han:"Đả hợp",nghia:"cuộc họp bàn, sự phối hợp"},
  {kanji:"話し合い",hira:"はなしあい",han:"Thoại hợp",nghia:"cuộc bàn bạc, thảo luận"},
  {kanji:"持ち合わせ",hira:"もちあわせ",han:"Trì hợp",nghia:"thứ mang theo, sẵn có"},
  {kanji:"知り合い",hira:"しりあい",han:"Tri hợp",nghia:"người quen biết"},
  {kanji:"待ち合わせ",hira:"まちあわせ",han:"Đãi hợp",nghia:"hẹn gặp, điểm hẹn"},
  {kanji:"刷り合わせ",hira:"すりあわせ",han:"Tứ hợp",nghia:"đối chiếu, hiệu chỉnh"},
  {kanji:"乗り合わせ",hira:"のりあわせ",han:"Thừa hợp",nghia:"cùng đi xe, tình cờ đi chung"},
  {kanji:"行き合い",hira:"いきあい",han:"Hành hợp",nghia:"tình cờ gặp"},
  {kanji:"出会い",hira:"であい",han:"Xuất hội",nghia:"sự gặp gỡ, cuộc gặp"},
  {kanji:"出会う",hira:"であう",han:"Xuất hội",nghia:"gặp gỡ, tình cờ gặp"},
  {kanji:"巡り合う",hira:"めぐりあう",han:"Tuần hợp",nghia:"tình cờ gặp, có duyên"},
  {kanji:"縁がある",hira:"えんがある",han:"Hữu duyên",nghia:"có duyên phận, có mối liên hệ"},
  {kanji:"縁を切る",hira:"えんをきる",han:"Thiết duyên",nghia:"cắt đứt mối quan hệ"},
  {kanji:"絆",hira:"きずな",han:"Kiên",nghia:"sợi dây liên kết, tình cảm gắn bó"},
  {kanji:"絆を結ぶ",hira:"きずなをむすぶ",han:"Kết kiên",nghia:"xây dựng mối quan hệ"},
  {kanji:"壁を乗り越える",hira:"かべをのりこえる",han:"Vượt tường",nghia:"vượt qua rào cản"},
  {kanji:"壁にぶつかる",hira:"かべにぶつかる",han:"Chạm tường",nghia:"gặp rào cản, bế tắc"},
  {kanji:"壁",hira:"かべ",han:"Tường",nghia:"bức tường, rào cản"},
  {kanji:"壁を作る",hira:"かべをつくる",han:"Tạo tường",nghia:"tạo ra rào cản, xây tường"},
  {kanji:"道を切り開く",hira:"みちをきりひらく",han:"Khai đạo",nghia:"mở đường, khai phá con đường"},
  {kanji:"道に迷う",hira:"みちにまよう",han:"Mê đạo",nghia:"lạc đường, không biết đường đi"},
  {kanji:"先を見越す",hira:"さきをみこす",han:"Tiên kiến",nghia:"nhìn xa, đề phòng trước"},
  {kanji:"先手を打つ",hira:"せんてをうつ",han:"Tiên thủ",nghia:"đi trước, ra tay trước"},
  {kanji:"後手に回る",hira:"ごてにまわる",han:"Hậu thủ",nghia:"bị động, ứng phó chậm"},
  {kanji:"手を打つ",hira:"てをうつ",han:"Xuất thủ",nghia:"hành động, ra tay"},
  {kanji:"手が回らない",hira:"てがまわらない",han:"Thủ bất cập",nghia:"không kịp, không đủ tay"},
  {kanji:"手に負えない",hira:"てにおえない",han:"Thủ bất kham",nghia:"không thể kiểm soát, quá tay"},
  {kanji:"手が届く",hira:"てがとどく",han:"Thủ cập",nghia:"với tới, đạt được"},
  {kanji:"手が届かない",hira:"てがとどかない",han:"Thủ bất cập",nghia:"không với tới, không đạt được"},
  {kanji:"胸に刻む",hira:"むねにきざむ",han:"Khắc tâm",nghia:"khắc ghi trong lòng"},
  {kanji:"胸を打つ",hira:"むねをうつ",han:"Đả hung",nghia:"cảm động, xúc động"},
  {kanji:"心が動く",hira:"こころがうごく",han:"Tâm động",nghia:"cảm động, xúc động"},
  {kanji:"心が折れる",hira:"こころがおれる",han:"Tâm chiết",nghia:"tâm lý suy sụp, mất ý chí"},
  {kanji:"心を込める",hira:"こころをこめる",han:"Tâm toàn",nghia:"dồn tâm huyết, làm hết lòng"},
  {kanji:"心を開く",hira:"こころをひらく",han:"Khai tâm",nghia:"mở lòng, cởi mở"},
  {kanji:"目が覚める",hira:"めがさめる",han:"Tỉnh mục",nghia:"tỉnh dậy, nhận ra"},
  {kanji:"目が離せない",hira:"めがはなせない",han:"Mục bất ly",nghia:"không thể rời mắt, cuốn hút"},
  {kanji:"目に余る",hira:"めにあまる",han:"Mục dư",nghia:"quá đáng, không thể bỏ qua"},
  {kanji:"気が向く",hira:"きがむく",han:"Khí hướng",nghia:"hứng lên, thích làm"},
  {kanji:"気が進まない",hira:"きがすすまない",han:"Khí bất tiến",nghia:"không hứng, không muốn"},
  {kanji:"気が重い",hira:"きがおもい",han:"Khí trọng",nghia:"nặng nề, lo lắng"},
  {kanji:"気が楽になる",hira:"きがらくになる",han:"Khí lạc",nghia:"nhẹ nhõm, thoải mái"},
  {kanji:"気が抜ける",hira:"きがぬける",han:"Khí thoát",nghia:"mất hết sức, buông lỏng"},
  {kanji:"気が散る",hira:"きがちる",han:"Khí tán",nghia:"mất tập trung, sao nhãng"},
  {kanji:"目指す",hira:"めざす",han:"Mục chỉ",nghia:"nhắm đến, hướng đến"},
  {kanji:"目覚める",hira:"めざめる",han:"Mục giác",nghia:"thức dậy, nhận ra"},
  {kanji:"振り向く",hira:"ふりむく",han:"Chấn hướng",nghia:"quay lại, nhìn lại"},
  {kanji:"振り出しに戻る",hira:"ふりだしにもどる",han:"Phục khởi",nghia:"trở về điểm xuất phát"},
  {kanji:"立ち向かう",hira:"たちむかう",han:"Lập hướng",nghia:"đương đầu, đối mặt"},
  {kanji:"乗り出す",hira:"のりだす",han:"Thừa xuất",nghia:"bắt đầu, tiến vào"},
  {kanji:"踏み出す",hira:"ふみだす",han:"Đạp xuất",nghia:"bước ra, khởi đầu"},
  {kanji:"歩み出す",hira:"あゆみだす",han:"Bộ xuất",nghia:"bước ra, tiến lên"},
  {kanji:"歩み寄る",hira:"あゆみよる",han:"Bộ ký",nghia:"tiến lại gần, thỏa hiệp"},
  {kanji:"寄り添う",hira:"よりそう",han:"Ký thiêm",nghia:"đồng hành, sát cánh bên"},
  {kanji:"寄り掛かる",hira:"よりかかる",han:"Ký quải",nghia:"dựa vào, tựa vào"},
  {kanji:"頼り切る",hira:"たよりきる",han:"Lại thiết",nghia:"hoàn toàn dựa vào, phụ thuộc"},
  {kanji:"頼りにする",hira:"たよりにする",han:"Lại",nghia:"dựa vào, tin tưởng"},
  {kanji:"頼りにならない",hira:"たよりにならない",han:"Không đáng tin",nghia:"không đáng tin, không đáng dựa"},
  {kanji:"打ち明ける",hira:"うちあける",han:"Đả minh",nghia:"tâm sự, bộc bạch thật lòng"},
  {kanji:"うち解ける",hira:"うちとける",han:"Đả giải",nghia:"cởi mở, thân thiện hơn"},
  {kanji:"奮い立つ",hira:"ふるいたつ",han:"Phấn lập",nghia:"phấn chấn, hăng hái"},
  {kanji:"奮い起こす",hira:"ふるいおこす",han:"Phấn khởi",nghia:"kích thích, phát huy"},
  {kanji:"奮い起きる",hira:"ふるいおきる",han:"Phấn khởi",nghia:"phấn chấn, vùng dậy"},
  {kanji:"踏ん張る",hira:"ふんばる",han:"Trụ",nghia:"cố gắng, kiên trì"},
  {kanji:"頑張る",hira:"がんばる",han:"Kiên trì",nghia:"cố gắng, nỗ lực"},
  {kanji:"踏ん張り",hira:"ふんばり",han:"Trụ lực",nghia:"sức chịu đựng, kiên trì"},
  {kanji:"頑張り",hira:"がんばり",han:"Kiên trì",nghia:"sự cố gắng, nỗ lực"},
  {kanji:"挫折",hira:"ざせつ",han:"Thoái chí",nghia:"thất bại, bỏ cuộc"},
  {kanji:"挫折する",hira:"ざせつする",han:"Thoái chí",nghia:"thất bại, bỏ cuộc"},
  {kanji:"立ち直る",hira:"たちなおる",han:"Lập trực",nghia:"hồi phục, đứng vững lại"},
  {kanji:"立ち直り",hira:"たちなおり",han:"Lập trực",nghia:"sự hồi phục, sự đứng vững lại"},
  {kanji:"もがく",hira:"もがく",han:"Vùng vẫy",nghia:"vùng vẫy, cố gắng thoát"},
  {kanji:"諦めない",hira:"あきらめない",han:"Bất đề",nghia:"không từ bỏ, kiên quyết"},
  {kanji:"前向き",hira:"まえむき",han:"Tiền hướng",nghia:"tích cực, hướng về phía trước"},
  {kanji:"後ろ向き",hira:"うしろむき",han:"Hậu hướng",nghia:"tiêu cực, hướng về phía sau"},
  {kanji:"上向き",hira:"うわむき",han:"Thượng hướng",nghia:"xu hướng tăng, lạc quan"},
  {kanji:"下向き",hira:"したむき",han:"Hạ hướng",nghia:"xu hướng giảm, bi quan"},
  {kanji:"成り行き",hira:"なりゆき",han:"Thành hành",nghia:"diễn biến, chiều hướng"},
  {kanji:"行き先",hira:"いきさき",han:"Hành tiên",nghia:"nơi đến, điểm đến"},
  {kanji:"行き場",hira:"いきば",han:"Hành trường",nghia:"nơi đến, chỗ đi"},
  {kanji:"居場所",hira:"いばしょ",han:"Cư trường sở",nghia:"chỗ đứng, nơi thuộc về"},
  {kanji:"立ち位置",hira:"たちいち",han:"Lập vị",nghia:"vị trí đứng, quan điểm"},
  {kanji:"強み",hira:"つよみ",han:"Cường",nghia:"điểm mạnh"},
  {kanji:"弱み",hira:"よわみ",han:"Nhược",nghia:"điểm yếu"},
  {kanji:"長所",hira:"ちょうしょ",han:"Trường sở",nghia:"điểm mạnh, ưu điểm"},
  {kanji:"短所",hira:"たんしょ",han:"Đoản sở",nghia:"điểm yếu, nhược điểm"},
  {kanji:"得意分野",hira:"とくいぶんや",han:"Đắc ý phân dã",nghia:"lĩnh vực sở trường"},
  {kanji:"苦手分野",hira:"にがてぶんや",han:"Khổ thủ phân dã",nghia:"lĩnh vực không giỏi"},
  {kanji:"立場",hira:"たちば",han:"Lập trường",nghia:"quan điểm, lập trường"},
  {kanji:"視点",hira:"してん",han:"Thị điểm",nghia:"quan điểm, góc nhìn"},
  {kanji:"観点",hira:"かんてん",han:"Quan điểm",nghia:"quan điểm, góc nhìn"},
  {kanji:"論点",hira:"ろんてん",han:"Luận điểm",nghia:"luận điểm, vấn đề tranh luận"},
  {kanji:"焦点",hira:"しょうてん",han:"Tiêu điểm",nghia:"tiêu điểm, trọng tâm"},
  {kanji:"重点",hira:"じゅうてん",han:"Trọng điểm",nghia:"trọng điểm, điểm quan trọng"},
  {kanji:"着眼点",hira:"ちゃくがんてん",han:"Trứ nhãn điểm",nghia:"điểm chú ý, điểm nhìn"},
  {kanji:"出発",hira:"しゅっぱつ",han:"Xuất phát",nghia:"khởi hành, xuất phát"},
  {kanji:"到着",hira:"とうちゃく",han:"Đáo trứ",nghia:"đến nơi, đến"},
  {kanji:"帰宅",hira:"きたく",han:"Quy trạch",nghia:"về nhà"},
  {kanji:"外出",hira:"がいしゅつ",han:"Ngoại xuất",nghia:"ra ngoài"},
  {kanji:"外泊",hira:"がいはく",han:"Ngoại bạc",nghia:"ở bên ngoài qua đêm"},
  {kanji:"帰省",hira:"きせい",han:"Quy tỉnh",nghia:"về thăm quê"},
  {kanji:"引越し",hira:"ひっこし",han:"Dẫn việt",nghia:"chuyển nhà"},
  {kanji:"転勤",hira:"てんきん",han:"Chuyển cần",nghia:"chuyển công tác"},
  {kanji:"入学",hira:"にゅうがく",han:"Nhập học",nghia:"nhập học"},
  {kanji:"卒業",hira:"そつぎょう",han:"Tốt nghiệp",nghia:"tốt nghiệp"},
  {kanji:"進学",hira:"しんがく",han:"Tiến học",nghia:"lên học trường cao hơn"},
  {kanji:"受験",hira:"じゅけん",han:"Thụ nghiệm",nghia:"dự thi, thi"},
  {kanji:"合格",hira:"ごうかく",han:"Hợp cách",nghia:"đỗ, vượt qua kỳ thi"},
  {kanji:"不合格",hira:"ふごうかく",han:"Bất hợp cách",nghia:"trượt, không qua"},
  {kanji:"資格",hira:"しかく",han:"Tư cách",nghia:"tư cách, bằng cấp"},
  {kanji:"免許",hira:"めんきょ",han:"Miễn hứa",nghia:"giấy phép, bằng lái"},
  {kanji:"認定",hira:"にんてい",han:"Nhận định",nghia:"công nhận, chứng nhận"},
  {kanji:"認証",hira:"にんしょう",han:"Nhận chứng",nghia:"xác thực, chứng nhận"},
  {kanji:"許可",hira:"きょか",han:"Hứa khả",nghia:"cho phép, cấp phép"},
  {kanji:"禁止",hira:"きんし",han:"Cấm chỉ",nghia:"cấm, cấm đoán"},
  {kanji:"制限",hira:"せいげん",han:"Chế hạn",nghia:"giới hạn, hạn chế"},
  {kanji:"規制",hira:"きせい",han:"Quy chế",nghia:"quy định, điều chỉnh"},
  {kanji:"監視",hira:"かんし",han:"Giám sát",nghia:"giám sát, theo dõi"},
  {kanji:"管理",hira:"かんり",han:"Quản lý",nghia:"quản lý"},
  {kanji:"運営",hira:"うんえい",han:"Vận doanh",nghia:"điều hành, vận hành"},
  {kanji:"維持",hira:"いじ",han:"Duy trì",nghia:"duy trì, giữ gìn"},
  {kanji:"改善",hira:"かいぜん",han:"Cải thiện",nghia:"cải thiện"},
  {kanji:"効率化",hira:"こうりつか",han:"Hiệu suất hoá",nghia:"nâng cao hiệu suất"},
  {kanji:"合理化",hira:"ごうりか",han:"Hợp lý hoá",nghia:"hợp lý hóa"},
  {kanji:"簡素化",hira:"かんそか",han:"Giản tố hoá",nghia:"đơn giản hóa"},
  {kanji:"共有",hira:"きょうゆう",han:"Cộng hữu",nghia:"chia sẻ, dùng chung"},
  {kanji:"提携",hira:"ていけい",han:"Đề huề",nghia:"hợp tác, liên kết"},
  {kanji:"連携",hira:"れんけい",han:"Liên huề",nghia:"phối hợp, liên kết"},
  {kanji:"協定",hira:"きょうてい",han:"Hiệp định",nghia:"hiệp định, thỏa thuận"},
  {kanji:"合意",hira:"ごうい",han:"Hợp ý",nghia:"đồng ý, thỏa thuận"},
  {kanji:"交渉",hira:"こうしょう",han:"Giao thiệp",nghia:"đàm phán, thương lượng"},
  {kanji:"妥協",hira:"だきょう",han:"Tuỳ nghị",nghia:"thỏa hiệp, nhượng bộ"},
  {kanji:"和解",hira:"わかい",han:"Hoà giải",nghia:"hòa giải, làm lành"},
  {kanji:"融和",hira:"ゆうわ",han:"Dung hoà",nghia:"hòa hợp, dung hòa"},
  {kanji:"融合",hira:"ゆうごう",han:"Dung hợp",nghia:"hợp nhất, kết hợp"},
  {kanji:"分裂",hira:"ぶんれつ",han:"Phân liệt",nghia:"phân liệt, chia rẽ"},
  {kanji:"対立",hira:"たいりつ",han:"Đối lập",nghia:"đối lập, mâu thuẫn"},
  {kanji:"摩擦",hira:"まさつ",han:"Ma sát",nghia:"ma sát, mâu thuẫn"},
  {kanji:"衝突",hira:"しょうとつ",han:"Xung đột",nghia:"xung đột, va chạm"},
  {kanji:"競合",hira:"きょうごう",han:"Cạnh hợp",nghia:"cạnh tranh, đối lập"},
  {kanji:"相互理解",hira:"そうごりかい",han:"Tương hỗ lý giải",nghia:"hiểu nhau, tương hiểu"},
  {kanji:"相互依存",hira:"そうごいぞん",han:"Tương hỗ y tồn",nghia:"phụ thuộc lẫn nhau"},
  {kanji:"共存",hira:"きょうぞん",han:"Cộng tồn",nghia:"cùng tồn tại, chung sống"},
  {kanji:"共生",hira:"きょうせい",han:"Cộng sinh",nghia:"cùng sống, cộng sinh"},
  {kanji:"多様性",hira:"たようせい",han:"Đa dạng tính",nghia:"tính đa dạng"},
  {kanji:"包括性",hira:"ほうかつせい",han:"Bao quát tính",nghia:"tính bao quát, toàn diện"},
  {kanji:"持続可能性",hira:"じぞくかのうせい",han:"Trì tục khả năng tính",nghia:"tính bền vững"},
  {kanji:"透明性",hira:"とうめいせい",han:"Thấu minh tính",nghia:"tính minh bạch"},
  {kanji:"信頼性",hira:"しんらいせい",han:"Tín lại tính",nghia:"độ tin cậy"},
  {kanji:"有効性",hira:"ゆうこうせい",han:"Hữu hiệu tính",nghia:"tính hiệu quả"},
  {kanji:"妥当性",hira:"だとうせい",han:"Tuỳ đương tính",nghia:"tính hợp lý, tính phù hợp"},
  {kanji:"公正性",hira:"こうせいせい",han:"Công chính tính",nghia:"tính công bằng"},
  {kanji:"必然性",hira:"ひつぜんせい",han:"Tất nhiên tính",nghia:"tính tất nhiên"},
  {kanji:"偶然性",hira:"ぐうぜんせい",han:"Ngẫu nhiên tính",nghia:"tính ngẫu nhiên"},
  {kanji:"独創性",hira:"どくそうせい",han:"Độc sáng tính",nghia:"tính sáng tạo độc đáo"},
  {kanji:"先進性",hira:"せんしんせい",han:"Tiên tiến tính",nghia:"tính tiên tiến"},
  {kanji:"革新性",hira:"かくしんせい",han:"Cách tân tính",nghia:"tính cách tân, đổi mới"},
];

const filtered = extra.filter(e => !existingSet.has(e.kanji));
console.log(`Adding ${filtered.length} new entries (from ${existing.length} to ${existing.length + filtered.length})`);

const combined = [...existing, ...filtered];
writeFileSync(filePath, JSON.stringify(combined, null, 2), 'utf8');
console.log(`Done. Total: ${combined.length} entries`);
